##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [3.13.0-B3] date: [Wed May 05 21:55:23 ICT 2021]
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = touch
MAKEFLAGS := --jobs=$(shell nproc)


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Os


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build
SIMULATOR_SRC_PATH=simulator
SIMULATOR_BUILD_DIR = $(BUILD_DIR)/simulator
######################################
# source
######################################
# C sources
C_SOURCES =  
C_SOURCES +=Core/Src/main.c 
C_SOURCES +=Core/Src/sys.c 
C_SOURCES +=Core/Src/delay.c 
C_SOURCES +=Core/Src/24c02.c 
C_SOURCES +=Core/Src/ctpiic.c 
C_SOURCES +=Core/Src/exti.c 
C_SOURCES +=Core/Src/ft5426.c 
C_SOURCES +=Core/Src/gt911.c 
C_SOURCES +=Core/Src/gui.c 
C_SOURCES +=Core/Src/iic.c 
C_SOURCES +=Core/Src/key.c 
C_SOURCES +=Core/Src/lcd.c 
C_SOURCES +=Core/Src/led.c 
C_SOURCES +=Core/Src/rtp.c 
C_SOURCES +=Core/Src/test.c 
C_SOURCES +=Core/Src/touch.c 
C_SOURCES +=Core/Src/usart.c 
C_SOURCES +=Core/Src/w25q64.c 
C_SOURCES +=Core/Src/spi.c 
C_SOURCES +=Core/Src/flash.c 
C_SOURCES +=Core/Src/adc.c 
C_SOURCES +=Core/Src/dac.c 
C_SOURCES +=Core/Src/wkup.c 
C_SOURCES +=Core/Src/pwm.c 
C_SOURCES +=Core/Src/iwdg.c 
C_SOURCES +=Core/Src/dma.c 
C_SOURCES +=Core/Src/timer.c 
C_SOURCES +=Core/Src/ws_spi.c 
C_SOURCES +=Core/Src/random.c 
C_SOURCES +=Core/Src/sdio_sdcard.c 
C_SOURCES +=Core/Src/fontupd.c 
C_SOURCES +=Core/Src/bmp.c 
C_SOURCES +=Core/Src/text.c 
C_SOURCES +=Core/Src/gif.c 
C_SOURCES +=Core/Src/tjpgd.c 
C_SOURCES +=Core/Src/piclib.c 
C_SOURCES +=Core/Src/ws_AT45DBXX.c 
C_SOURCES +=Core/Src/custom_malloc.c 
C_SOURCES +=Core/Src/as5600.c 
C_SOURCES +=Core/Src/aht10.c 
C_SOURCES +=Core/Src/bh1750.c 
C_SOURCES +=Core/Src/tcs34725.c 

C_SOURCES +=Core/Src/usb_bsp.c 
C_SOURCES +=Core/Src/usb_cdc.c 
C_SOURCES +=Core/Src/usb_vcp.c 
C_SOURCES +=Core/Src/usbd_desc.c 
C_SOURCES +=Core/Src/usbd_usr.c 

# C_SOURCES +=Core/Src/stm32f4xx_it.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/misc.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_adc.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_can.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_crc.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_cryp.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_cryp_aes.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_cryp_des.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_cryp_tdes.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_dac.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_dbgmcu.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_dcmi.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_dma.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_dma2d.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_exti.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_flash.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_flash_ramfunc.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_fmc.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_fsmc.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_gpio.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_hash.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_hash_md5.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_hash_sha1.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_i2c.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_iwdg.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_ltdc.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_pwr.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_rcc.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_rng.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_rtc.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_sai.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_sdio.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_spi.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_syscfg.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_tim.c 
C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_usart.c 
# C_SOURCES +=Drivers/STM32F4xx_FWLIB/src/stm32f4xx_wwdg.c 
C_SOURCES +=Core/Src/system_stm32f4xx.c 
C_SOURCES +=device/lv_port_disp.c 
C_SOURCES +=device/lv_port_indev.c 
# C_SOURCES +=ui/ui_test.c 
# C_SOURCES +=ui/simpson.c 

C_SOURCES += Core/Lib/FATFS/exfuns/exfuns.c
C_SOURCES += Core/Lib/FATFS/fattester.c
C_SOURCES += Core/Lib/FATFS/src/diskio.c
C_SOURCES += Core/Lib/FATFS/src/ff.c

C_SOURCES += Drivers/STM32_USB_Device_Library/Class/cdc/src/usbd_cdc_core.c
C_SOURCES += Drivers/STM32_USB_Device_Library/Core/src/usbd_core.c
C_SOURCES += Drivers/STM32_USB_Device_Library/Core/src/usbd_ioreq.c
C_SOURCES += Drivers/STM32_USB_Device_Library/Core/src/usbd_req.c
C_SOURCES += Drivers/STM32_USB_OTG_Driver/src/usb_core.c
C_SOURCES += Drivers/STM32_USB_OTG_Driver/src/usb_dcd_int.c
C_SOURCES += Drivers/STM32_USB_OTG_Driver/src/usb_dcd.c



# sources for simulator
SIMULATOR_SOURCES +=$(SIMULATOR_SRC_PATH)/mouse_cursor_icon.c
SIMULATOR_SOURCES +=$(SIMULATOR_SRC_PATH)/simulator.c

# common source
SHARED_SOURCES += \
ui_test.c  \
ui/simpson.c \
ui/leg.c \


# LVGL includes
LVGL_DIR = .
LVGL_DIR_NAME = lvgl
include $(LVGL_DIR)/$(LVGL_DIR_NAME)/lvgl.mk
LVGL_SOURCES := $(CSRCS)
SHARED_SOURCES += $(LVGL_SOURCES)

CSRCS :=
include lv_drivers/lv_drivers.mk
LV_DRIVER_SOURCES := $(CSRCS)

C_SOURCES += $(SHARED_SOURCES)

# ASM sources
ASM_SOURCES =  \
startup_stm32f407xx.s


#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m4

# fpu
FPU = -mfpu=fpv4-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_STDPERIPH_DRIVER \
-DSTM32F40_41xxx \
-DUSE_USB_OTG_FS


# AS includes
AS_INCLUDES = 



# C includes
C_INCLUDES =  \
-ICore/Inc \
-ICore/Lib/FATFS/exfuns \
-ICore/Lib/FATFS/src \
-IDrivers/STM32F4xx_FWLIB/inc \
-IDrivers/CMSIS/Device/ST/STM32F4xx/Include \
-IDrivers/CMSIS/Include \
-I. \
-Iui \
-Ilvgl \
-Idevice \
-Ilv_demos \
-Ilv_drivers \
-IDrivers/STM32_USB_OTG_Driver/inc \
-IDrivers/STM32_USB_Device_Library/Core/inc \
-IDrivers/STM32_USB_Device_Library/Class/cdc/inc \



# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS = $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections -Wno-missing-braces -std=c11

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32F407VGTx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections -Wl,--print-memory-usage -u _printf_float

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))



#######################################
# simulator params
#######################################
S_SRCS = $(SIMULATOR_SOURCES)
S_SRCS += $(SHARED_SOURCES)
S_SRCS += $(LV_DRIVER_SOURCES)

S_OBJECTS = $(patsubst %,$(SIMULATOR_BUILD_DIR)/%,$(S_SRCS:.c=.o))

S_CC = gcc
S_CFLAGS = 
S_DEFINES = -D SIMULATOR=1 -D LV_LVGL_H_INCLUDE_SIMPLE=0 -D LV_BUILD_TEST=0 -D STM32F40_41xxx -D USE_STDPERIPH_DRIVER

S_COMPILE = $(S_CC) $(S_CFLAGS) $(C_INCLUDES) $(S_INCLUDES) $(S_DEFINES)
S_BIN = $(SIMULATOR_BUILD_DIR)/$(TARGET)
S_LDLIBS = -lSDL2 -lm





$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		






simulator: $(S_BIN)
	$(info simulator build completed, try to run...)
	$(SIMULATOR_BUILD_DIR)/$(TARGET)

$(SIMULATOR_BUILD_DIR)/%.o: %.c
	@mkdir -p $(dir $@)
	@$(S_COMPILE) -c -o "$@" "$<"

$(S_BIN): $(S_OBJECTS)	
	@mkdir -p $(SIMULATOR_BUILD_DIR)
	$(S_CC) -o $(S_BIN) $(S_OBJECTS) $(S_LDFLAGS) ${S_LDLIBS}







#######################################
# clean up
#######################################
clean:
	-rm -fR $(BUILD_DIR)
  
#######################################
# dependencies
#######################################
# flash
#######################################
flash: all
	openocd -f interface/stlink.cfg -f target/stm32f4x.cfg -c "transport select hla_swd" -c "program ${BUILD_DIR}/${TARGET}.elf verify reset exit"
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***